
services:
  spring_app:
    build: .
    container_name: bank_spring
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:8080"
    networks:
      - MNBank

networks:
  MNBank:
    external: true
