
services:
  spring_app:
    build: .
    container_name: bank_spring
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: LaLa27418182
    ports:
      - "5000:8080"
    networks:
      - MNBank

networks:
  MNBank:
    external: true
