version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: LaLa27418182
    ports:
      - "5000:8080"
    networks:
      - my_network
    volumes:
      - ./backend:/app

networks:
  my_network:
    external: true
