version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:1212/postgres
    ports:
      - "5000:8080"
    volumes:
      - ./backend:/app
